language: python

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/heavenshell/py-robo-google_image

script: python setup.py test
